# Jupyter Book v1 configuration

title: "Interactive Physics Simulations"
author: "Your Name"
logo: ""

only_build_toc_files: true

execute:
  execute_notebooks: "off"

html:
  favicon: ""
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
